CALC_RESP_EXAMPLE = {
  "Gehennas":{
    "boss_id":18,
    "boss_name":"Gehennas",
    "bs_casts":0,
    "bt_count":5,
    "cleave_count":20,
    "defiance_points":5,
    "demo_casts":0,
    "enemies_in_combat":1,
    "execute_dmg":0,
    "friendlies_in_combat":1,
    "goa_procs":0,
    "hp_gains":401.0,
    "hs_casts":1,
    "hs_count":1,
    "player_class":"Warrior",
    "player_name":"Aemin",
    "rage_gains":19,
    "realm":"Skeram",
    "revenge_casts":5,
    "revenge_count":3,
    "shield_slam_casts":0,
    "shield_slam_count":0,
    "sunder_casts":7,
    "sunder_count":4,
    "t1_set":False,
    "thunderclap_casts":0,
    "time":33.226,
    "total_damage":26098,
    "total_threat":30527.5,
    "total_threat_defiance":45196.84,
    "tps":1369.1789562390898,
    "unmodified_tps":918.7834828146632
  }
}

THREAT_RESP_EXAMPLE =[
  {
    "name":"BattleShout",
    "threat_type":"Flat",
    "val":56
  },
  {
    "name":"Cleave",
    "threat_type":"Flat",
    "val":100
  },
  {
    "name":"DefensiveStance",
    "threat_type":"Modifier",
    "val":1.3
  },
  {
    "name":"Defiance0",
    "threat_type":"Modifier",
    "val":1
  },
  {
    "name":"Defiance1",
    "threat_type":"Modifier",
    "val":1.03
  },
  {
    "name":"Defiance2",
    "threat_type":"Modifier",
    "val":1.06
  },
  {
    "name":"Defiance3",
    "threat_type":"Modifier",
    "val":1.09
  },
  {
    "name":"Defiance4",
    "threat_type":"Modifier",
    "val":1.12
  },
  {
    "name":"Defiance5",
    "threat_type":"Modifier",
    "val":1.15
  },
  {
    "name":"DemoShout",
    "threat_type":"Flat",
    "val":43
  },
  {
    "name":"Execute",
    "threat_type":"Flat",
    "val":1
  },
  {
    "name":"GiftOfArthas",
    "threat_type":"Flat",
    "val":90
  },
  {
    "name":"Healing",
    "threat_type":"Flat",
    "val":0.5
  },
  {
    "name":"HeroicStrike",
    "threat_type":"Flat",
    "val":145
  },
  {
    "name":"RageGain",
    "threat_type":"Flat",
    "val":5
  },
  {
    "name":"Revenge",
    "threat_type":"Flat",
    "val":315
  },
  {
    "name":"ShieldSlam",
    "threat_type":"Flat",
    "val":250
  },
  {
    "name":"SunderArmor",
    "threat_type":"Flat",
    "val":261
  },
  {
    "name":"ThunderClap",
    "threat_type":"Flat",
    "val":104.0
  },
  {
    "name":"Tier1Bonus",
    "threat_type":"Modifier",
    "val":1.15
  },
  {
    "name":"Damage",
    "threat_type":"Flat",
    "val":1
  }
]

HEARTBEAT = {'status': 'OK'}