CALC_RESP_EXAMPLE = {
    "Magmadar": { 
        "boss_id":12,
        "boss_name":"Magmadar",
        "bs_casts":0,
        "bs_rank":11551,
        "bt_casts":10,
        "cleave_casts":0,
        "cleave_hits":0,
        "defiance_points":5,
        "demo_casts":0,
        "disarm_hits":0,
        "enemies_in_combat":1,
        "execute_dmg":0,
        "friendlies_in_combat":1,
        "goa_procs":0,
        "hamstring_hits":0,
        "hp_gains":1001.0,
        "hs_casts":28,
        "hs_hits":21,
        "hs_rank":11567,
        "mockingblow_hits":0,
        "no_d_stance": { 
            "total_damage":0,
            "execute_dmg":0,
            "sunder_misses":0,
            "sunder_casts":0,
            "shield_slam_hits":0,
            "revenge_hits":0,
            "hs_hits":0,
            "time":0,
            "mockingblow_hits":0,
            "hamstring_hits":0,
            "thunderclap_hits":0,
            "disarm_hits":0,
            "shieldbash_hits":0,
            "enemies_in_combat":0,
            "cleave_hits":0,
            "boss_name":"Magmadar",
            "boss_id":12,
            "friendlies_in_combat":1,
            "shield_slam_casts":0,
            "revenge_casts":0,
            "hs_casts":0,
            "goa_procs":0,
            "bs_casts":0,
            "demo_casts":0,
            "thunderclap_casts":0,
            "bt_casts":0,
            "cleave_casts":0,
            "bs_rank":11551,
            "revenge_rank":11601,
            "hs_rank":11567,
            "rage_gains":0,
            "hp_gains":0,
            "sunder_hits":0
        },
        "player_class":"Warrior",
        "player_name":"Aemin",
        "rage_gains":53,
        "realm":"Skeram",
        "revenge_casts":4,
        "revenge_hits":3,
        "revenge_rank":11601,
        "shield_slam_casts":0,
        "shield_slam_hits":0,
        "shieldbash_hits":0,
        "sunder_casts":21,
        "sunder_hits":17,
        "t1_set": False,
        "thunderclap_hits":0,
        "time":63.191,
        "total_damage":27245,
        "total_threat":35672.0,
        "total_threat_defiance":53329.63999999999,
        "tps":856.057666439841,
        "unmodified_tps":576.6248358152268
    }
}

THREAT_RESP_EXAMPLE = [
  {
    "name":"BattleShout6",
    "threat_type":"Flat",
    "val":56
  },
  {
    "name":"BattleShout7",
    "threat_type":"Flat",
    "val":70
  },
  {
    "name":"BattleStance",
    "threat_type":"Modifier",
    "val":0.8
  },
  {
    "name":"BerserkerStance",
    "threat_type":"Modifier",
    "val":0.8
  },
  {
    "name":"Cleave",
    "threat_type":"Flat",
    "val":100
  },
  {
    "name":"DefensiveStance",
    "threat_type":"Modifier",
    "val":1.3
  },
  {
    "name":"Defiance0",
    "threat_type":"Modifier",
    "val":1
  },
  {
    "name":"Defiance1",
    "threat_type":"Modifier",
    "val":1.03
  },
  {
    "name":"Defiance2",
    "threat_type":"Modifier",
    "val":1.06
  },
  {
    "name":"Defiance3",
    "threat_type":"Modifier",
    "val":1.09
  },
  {
    "name":"Defiance4",
    "threat_type":"Modifier",
    "val":1.12
  },
  {
    "name":"Defiance5",
    "threat_type":"Modifier",
    "val":1.15
  },
  {
    "name":"DemoShout",
    "threat_type":"Flat",
    "val":43
  },
  {
    "name":"Disarm",
    "threat_type":"Flat",
    "val":104
  },
  {
    "name":"Execute",
    "threat_type":"Flat",
    "val":1
  },
  {
    "name":"GiftOfArthas",
    "threat_type":"Flat",
    "val":90
  },
  {
    "name":"Hamstring",
    "threat_type":"Flat",
    "val":145
  },
  {
    "name":"Healing",
    "threat_type":"Flat",
    "val":0.5
  },
  {
    "name":"HeroicStrike8",
    "threat_type":"Flat",
    "val":145
  },
  {
    "name":"HeroicStrike9",
    "threat_type":"Flat",
    "val":175
  },
  {
    "name":"MockingBlow",
    "threat_type":"Flat",
    "val":250
  },
  {
    "name":"RageGain",
    "threat_type":"Flat",
    "val":5
  },
  {
    "name":"Revenge5",
    "threat_type":"Flat",
    "val":315
  },
  {
    "name":"Revenge6",
    "threat_type":"Flat",
    "val":355
  },
  {
    "name":"ShieldBash",
    "threat_type":"Flat",
    "val":180
  },
  {
    "name":"ShieldSlam",
    "threat_type":"Flat",
    "val":250
  },
  {
    "name":"SunderArmor",
    "threat_type":"Flat",
    "val":261
  },
  {
    "name":"ThunderClap",
    "threat_type":"Flat",
    "val":130
  },
  {
    "name":"Tier1Bonus",
    "threat_type":"Modifier",
    "val":1.15
  },
  {
    "name":"Damage",
    "threat_type":"Flat",
    "val":1
  }
]

HEARTBEAT = {'status': 'OK'}

CALC_RESP_DRUID_EXAMPLE = {}